FEM-2411 treat ima dai  live  ad DVR so ad will continue from last watched pos
kaltura/playkit-android-ima pull request #56
Opened 2019-03-10 16:35 UTC by giladna

2019-03-11 04:28 UTC, GouravSna approved these changes

2019-03-11 05:42 UTC, OrenMe requested changes

2019-03-11 05:42 UTC, OrenMe commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/imadai/IMADAIPlugin.java
> +                return PKMediaEntry.MediaEntryType.DvrLive; // need to make it LiveDvr so resume will continue from lasr pos.
If stream is not DVR then this is incorrect, stream should resume from last live position, wether it’s inside ad or after it.

2019-05-12 09:28 UTC, OrenMe commented
not a bug

2019-05-12 09:28 UTC, closed without merging