FEM-2677 companion ad support
kaltura/playkit-android-ima pull request #85
Opened 2019-10-02 13:32 UTC by giladna

return new IMAConfig().setAdTagUrl(adTagUrl).
                                              setVideoMimeTypes(videoMimeTypes).
                                              setAlwaysStartWithPreroll(true).setAdLoadTimeOut(8).
                                              setCompanionAdConfig(companionAdSlot, 728, 90);

2019-10-03 13:03 UTC, GouravSna approved these changes

2019-10-23 12:58 UTC, noamtamim requested changes

2019-10-23 12:58 UTC, noamtamim commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/CompanionAdConfig.java
> +    private int companionAdHeight = 90;
Remove the defaults

2019-10-23 12:58 UTC, noamtamim commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/IMAConfig.java
Remove

2019-10-23 12:58 UTC, noamtamim commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/IMAPlugin.java
> +            if (adConfig.getCompanionAdConfig() != null && adCompanionViewGroup != null) {
Check width, height too

2019-10-23 12:58 UTC, noamtamim commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/IMAPlugin.java
> +        if (PKAdErrorType.COMPANION_AD_LOADING_FAILED.equals(errorType)) {
Check if we can report non-fatal error

2019-10-23 15:54 UTC, giladna commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/CompanionAdConfig.java
> +    private int companionAdHeight = 90;
done

2019-10-23 16:12 UTC, giladna commented on imaplugin/src/main/java/com/kaltura/playkit/plugins/ima/IMAPlugin.java
> +        if (PKAdErrorType.COMPANION_AD_LOADING_FAILED.equals(errorType)) {
done

2019-10-23 16:46 UTC, noamtamim approved these changes

2019-10-23 19:55 UTC, merged